[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/edirstat"]

[workspace.package]
version = "2.1.0"
edition = "2024"
license = "MIT"
authors = ["Cody Wyatt Neiman (xangelix) <neiman@cody.to>"]
repository = "https://github.com/xangelix/edirstat"

# [patch.crates-io]
# egui-table-kit = { path = "../egui-table-kit" }

[profile.release]
panic = "abort"
strip = true
lto = "thin"
# debug = true
codegen-units = 1
