#!/usr/bin/env bash
# Download the pinned Noto source fonts for the subsetted-font build pipeline
# (see crates/edirstat-gui/build.rs and scripts/subset_fonts.py).
#
# The fonts land in crates/edirstat-gui/assets/fonts/raw/ and are git-ignored:
# they are far too large to commit (~24 MB). The repo commits deterministic
# ~1.45 MB subsets generated by scripts/subset_fonts.py instead.
# Each download is verified against the hard-coded SHA-256 below.
#
# Sources (pinned to commits so the checksums are stable):
#   - NotoSans{SC,TC,JP,KR}-Regular.otf: notofonts/noto-cjk, Sans/SubsetOTF
#     (static, CFF).
#   - NotoSans{Bengali,Devanagari,Arabic}-Regular.ttf: google/fonts variable
#     fonts [wdth,wght], whose default instance (wght=400, wdth=100) is exactly
#     Regular — saved under the uniform -Regular name the pipeline expects.
set -euo pipefail

cd "$(dirname "$0")/.."
FONTS_DIR="crates/edirstat-gui/assets/fonts/raw"
mkdir -p "$FONTS_DIR"

CJK_COMMIT="f8d157532fbfaeda587e826d4cd5b21a49186f7c" # notofonts/noto-cjk main
GFONTS_COMMIT="5e35378e6bda803962ee6fd257e444a7d459660d" # google/fonts main
CJK_BASE="https://raw.githubusercontent.com/notofonts/noto-cjk/$CJK_COMMIT/Sans/SubsetOTF"
GFONTS_BASE="https://raw.githubusercontent.com/google/fonts/$GFONTS_COMMIT/ofl"

# <target filename>|<url>|<sha256>
FONTS=(
    "NotoSansSC-Regular.otf|$CJK_BASE/SC/NotoSansSC-Regular.otf|faa6c9df652116dde789d351359f3d7e5d2285a2b2a1f04a2d7244df706d5ea9"
    "NotoSansTC-Regular.otf|$CJK_BASE/TC/NotoSansTC-Regular.otf|5bab0cb3c1cf89dde07c4a95a4054b195afbcfe784d69d75c340780712237537"
    "NotoSansJP-Regular.otf|$CJK_BASE/JP/NotoSansJP-Regular.otf|dff723ba59d57d136764a04b9b2d03205544f7cd785a711442d6d2d085ac5073"
    "NotoSansKR-Regular.otf|$CJK_BASE/KR/NotoSansKR-Regular.otf|69975a0ac8472717870aefeab0a4d52739308d90856b9955313b2ad5e0148d68"
    "NotoSansBengali-Regular.ttf|$GFONTS_BASE/notosansbengali/NotoSansBengali%5Bwdth,wght%5D.ttf|dcd42978094e584a849c84a51450eeac40c8826057d566ea6d4b9627a403a05a"
    "NotoSansDevanagari-Regular.ttf|$GFONTS_BASE/notosansdevanagari/NotoSansDevanagari%5Bwdth,wght%5D.ttf|9ce7b04f60e363d8870e5997744cf85cf69d38a4d7d129d364d92a3b14b461d7"
    "NotoSansArabic-Regular.ttf|$GFONTS_BASE/notosansarabic/NotoSansArabic%5Bwdth,wght%5D.ttf|63111b5b2e074dd48cc67692e0a2726d86ee94c1c37fe8598257b7b4e87e869e"
    "NotoSansSymbols2-Regular.ttf|$GFONTS_BASE/notosanssymbols2/NotoSansSymbols2-Regular.ttf|7d5fb73b7ca67a6798101741f5d280a3d016a56a197afcd4199dbb57b4b82a21"
)

for entry in "${FONTS[@]}"; do
    IFS='|' read -r name url sha256 <<<"$entry"
    dest="$FONTS_DIR/$name"
    if [[ -f $dest ]] && echo "$sha256  $dest" | sha256sum -c --status -; then
        echo "==> $name already present and verified"
        continue
    fi
    tmp="$dest.tmp"
    echo "==> Downloading $name"
    curl -fSL --retry 3 -o "$tmp" "$url"
    if ! echo "$sha256  $tmp" | sha256sum -c - | sed 's/\.tmp//'; then
        rm -f "$tmp"
        echo "error: checksum mismatch for $name — not installing" >&2
        exit 1
    fi
    mv "$tmp" "$dest"
done

# The build script only watches the fonts dir once it exists; touch build.rs
# so the next cargo invocation re-runs it and picks up a first-time fetch.
touch crates/edirstat-gui/build.rs

echo "==> Done. Raw fonts downloaded to $FONTS_DIR. Run scripts/subset_fonts.py to generate subsets."
