use std::path::{Path, PathBuf};

fn main() -> std::io::Result<()> {
    // Pack assets (licenses subdirectory only).
    include_packed::Config::new(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/licenses"))
        .level(15)
        .build()
        .map_err(std::io::Error::other)?;

    let out_dir = std::env::var("OUT_DIR")
        .map(PathBuf::from)
        .map_err(std::io::Error::other)?;
    let charset_path = out_dir.join("fluent_charset.txt");

    // Static message cache, plus the charset corpus the font subsetter consumes.
    fluent_zero_build::FluentZeroBuilder::new(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/assets/locales"
    ))
    .export_charset(&charset_path)
    .generate();

    println!("cargo:rerun-if-env-changed=EDIRSTAT_MACOS_APPSTORE");
    println!("cargo:rerun-if-env-changed=EDIRSTAT_APP_SANDBOX");

    embed_fallback_fonts(&out_dir)
}

/// Embeds the committed subsetted fallback fonts in `assets/fonts/` into
/// `$OUT_DIR/subset_fonts.rs`, the font table `gui::fonts` embeds.
///
/// These fonts are pre-subsetted down to the fluent charset corpus via
/// `scripts/subset_fonts.py` (see `scripts/update_fonts.sh`) so they are
/// self-contained for crates.io packaging and CI/CD without build-time Python.
fn embed_fallback_fonts(out_dir: &Path) -> std::io::Result<()> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let fonts_dir = manifest_dir.join("assets/fonts");

    if fonts_dir.is_dir() {
        println!("cargo:rerun-if-changed={}", fonts_dir.display());
    }

    let fonts = collect_font_files(&fonts_dir);
    if fonts.is_empty() {
        println!(
            "cargo:warning=edirstat-gui: no fallback fonts found in {} — building without non-Latin fallback fonts",
            fonts_dir.display()
        );
        return write_subset_fonts_rs(out_dir, &[]);
    }

    write_subset_fonts_rs(out_dir, &fonts)
}

/// All `.ttf`/`.otf` files in `dir` (excluding subdirectories like `raw/`),
/// sorted for a deterministic table.
fn collect_font_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            let is_font = path.extension().is_some_and(|ext| {
                ext.eq_ignore_ascii_case("ttf") || ext.eq_ignore_ascii_case("otf")
            });
            if path.is_file() && is_font {
                files.push(path);
            }
        }
    }
    files.sort();
    files
}

fn write_subset_fonts_rs(out_dir: &Path, fonts: &[PathBuf]) -> std::io::Result<()> {
    let mut contents = String::from(
        "// @generated by build.rs — subsetted non-Latin fallback fonts\npub(super) const SUBSET_FONTS: &[(&str, &[u8])] = &[\n",
    );
    for font in fonts {
        let name = font
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unknown");
        let file_name = font.file_name().and_then(|s| s.to_str()).unwrap_or("");
        contents.push_str(&format!(
            "    ({name:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/fonts/{file_name}\"))),\n"
        ));
    }
    contents.push_str("];\n");
    std::fs::write(out_dir.join("subset_fonts.rs"), contents)
}
