name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/xangelix-pub/containers/arch-rust-nightly-pin-common:latest
      options: --user root # How I wish this were GitLab

    steps:
      - uses: actions/checkout@v6

      - name: Cache dependencies
        uses: swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check for unused dependencies
        run: cargo shear

      - name: Run tests (no default features)
        run: cargo test --no-default-features

      - name: Run tests
        run: cargo test
