name: Deploy Landing Page to GH Pages

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - ".github/workflows/deploy-web.yml"

# Core permissions required for native GitHub Actions Pages deployments
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-web:
    name: Deploy Web (Arch Container)
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/xangelix-pub/containers/arch
      options: --user root # How I wish this were GitLab

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Install System Dependencies
        run: |
          paru -Syu --noconfirm zola nodejs npm

      - name: Install Node Dependencies & Build Assets
        run: |
          cd web
          npm ci
          npm run build:assets

      - name: Build Zola Site
        run: |
          cd web
          zola build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./web/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
