name: Upload Release Binary

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-linux:
    name: Build & Upload Linux Asset
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/xangelix-pub/containers/arch-rust-nightly-pin-common:latest
      options: --user root # How I wish this were GitLab

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: swatinem/rust-cache@v2

      - name: Compile optimized release binary
        run: cargo build --release

      - name: Upload Asset to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/edirstat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
