base_url = "https://edirstat.com"
title = "eDirStat"
description = "Modern, high-performance, cross-platform disk usage analyzer written in Rust."
default_language = "en"
output_dir = "public"

[extra]
itch_io_url = "https://xangelix.itch.io/edirstat"
github_url = "https://github.com/xangelix/edirstat"
version = "2.0.1"
license = "MIT"
